/* The iPhone Guy Android Cleaner - Shared Knowledge service v2 (v0.15.1)
   IMPORTANT: keep your existing SHEET_ID and API_KEY values when replacing v1.
   After saving: Deploy > Manage deployments > Edit > New version > Deploy.
*/
const SHEET_ID = 'PASTE_GOOGLE_SHEET_ID_HERE';
const API_KEY = 'CHANGE_THIS_TO_A_LONG_RANDOM_SECRET';
const APPS = 'Apps';
const EVENTS = 'Events';
const SNAPSHOTS = 'StoreSnapshots';
const APP_HEADERS = ['package','app_name','reputation','safe_votes','malware_votes','repair_yes','repair_no','repair_unsure','removals','observations','solo_yes','solo_no','solo_unsure','group_yes','group_no','group_unsure','popup_solo_yes','popup_group_yes','stores_seen','last_seen','updated_at'];
const SNAP_HEADERS = ['store_id','package','app_name','reputation','safe_mark','malware_mark','repair_yes','repair_no','repair_unsure','removals','observations','solo_yes','solo_no','solo_unsure','group_yes','group_no','group_unsure','popup_solo_yes','popup_group_yes','sha256','updated_at'];
function doGet(){return json_({ok:true,message:'Android Cleaner Shared Knowledge is online'});}
function doPost(e){try{const q=JSON.parse((e.postData&&e.postData.contents)||'{}');if(!q.api_key||q.api_key!==API_KEY)return json_({ok:false,error:'Invalid API key'});ensure_();if(q.op==='ping')return json_({ok:true,message:'Shared Knowledge online'});if(q.op==='pull')return json_({ok:true,apps:readApps_()});if(q.op==='snapshot'||q.op==='bootstrap'){snapshot_(q);return json_({ok:true});}if(q.op==='classification'){classification_(q);return json_({ok:true});}if(q.op==='repair'){repair_(q);return json_({ok:true});}return json_({ok:false,error:'Unknown operation'});}catch(err){return json_({ok:false,error:String(err)});}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function ss_(){return SpreadsheetApp.openById(SHEET_ID);}
function sheet_(name,headers){const ss=ss_();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(headers);else{const old=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),headers.length)).getValues()[0];headers.forEach((h,i)=>{if(old[i]!==h)sh.getRange(1,i+1).setValue(h);});}return sh;}
function ensure_(){sheet_(APPS,APP_HEADERS);sheet_(EVENTS,['event_id','timestamp','store_id','type','package','app_name','value','reason','group_id','note']);sheet_(SNAPSHOTS,SNAP_HEADERS);}
function readApps_(){const sh=sheet_(APPS,APP_HEADERS),v=sh.getDataRange().getValues();if(v.length<2)return[];return v.slice(1).filter(r=>r[0]).map(r=>{let o={};APP_HEADERS.forEach((h,i)=>o[h]=r[i]);return o;});}
function num_(x){const n=Number(x||0);return isNaN(n)?0:n;}
function snapshot_(q){const store=String(q.store_id||'').trim();if(!store)throw new Error('Store ID required');const sh=sheet_(SNAPSHOTS,SNAP_HEADERS),vals=sh.getDataRange().getValues(),idx={};for(let i=1;i<vals.length;i++)idx[String(vals[i][0])+'\u0000'+String(vals[i][1])]=i+1;const now=new Date().toISOString();(q.apps||[]).forEach(a=>{const pkg=String(a.package||'').trim();if(!pkg)return;const rep=String(a.reputation||'UNKNOWN');const row=[store,pkg,a.app_name||pkg,rep,rep==='KNOWN SAFE'?1:0,rep==='KNOWN MALWARE'?1:0,num_(a.repair_yes),num_(a.repair_no),num_(a.repair_unsure),num_(a.removals),num_(a.observations),num_(a.solo_yes),num_(a.solo_no),num_(a.solo_unsure),num_(a.group_yes),num_(a.group_no),num_(a.group_unsure),num_(a.popup_solo_yes),num_(a.popup_group_yes),a.sha256||'',now];const k=store+'\u0000'+pkg;if(idx[k])sh.getRange(idx[k],1,1,row.length).setValues([row]);else{sh.appendRow(row);idx[k]=sh.getLastRow();}});rebuildApps_();}
function rebuildApps_(){const snap=sheet_(SNAPSHOTS,SNAP_HEADERS),v=snap.getDataRange().getValues(),agg={},now=new Date().toISOString();for(let i=1;i<v.length;i++){const r=v[i],pkg=String(r[1]||'');if(!pkg)continue;let a=agg[pkg];if(!a)a=agg[pkg]={package:pkg,app_name:r[2]||pkg,safe:0,mal:0,ry:0,rn:0,ru:0,rem:0,obs:0,sy:0,sn:0,su:0,gy:0,gn:0,gu:0,psy:0,pgy:0,stores:{},last:''};a.app_name=r[2]||a.app_name;a.safe+=num_(r[4]);a.mal+=num_(r[5]);a.ry+=num_(r[6]);a.rn+=num_(r[7]);a.ru+=num_(r[8]);a.rem+=num_(r[9]);a.obs+=num_(r[10]);a.sy+=num_(r[11]);a.sn+=num_(r[12]);a.su+=num_(r[13]);a.gy+=num_(r[14]);a.gn+=num_(r[15]);a.gu+=num_(r[16]);a.psy+=num_(r[17]);a.pgy+=num_(r[18]);a.stores[String(r[0])]=1;if(String(r[20]||'')>a.last)a.last=String(r[20]||'');}
 const sh=sheet_(APPS,APP_HEADERS);if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).clearContent();Object.keys(agg).sort().forEach(pkg=>{const a=agg[pkg];let rep='UNKNOWN';if(a.safe>0&&a.mal===0)rep='KNOWN SAFE';else if(a.mal>0&&a.safe===0)rep='KNOWN MALWARE';else if(a.safe>0&&a.mal>0)rep='CONFLICT';sh.appendRow([pkg,a.app_name,rep,a.safe,a.mal,a.ry,a.rn,a.ru,a.rem,a.obs,a.sy,a.sn,a.su,a.gy,a.gn,a.gu,a.psy,a.pgy,Object.keys(a.stores).length,a.last||now,now]);});}
function event_(q,type,pkg,name,value,reason,group,note){sheet_(EVENTS,['event_id','timestamp','store_id','type','package','app_name','value','reason','group_id','note']).appendRow([Utilities.getUuid(),new Date().toISOString(),q.store_id||'',type,pkg,name||pkg,value||'',reason||'',group||'',note||'']);}
function classification_(q){if(!q.package)return;event_(q,'classification',q.package,q.app_name,String(q.classification||''),'','',q.note);/* Snapshot on next Sync Now is authoritative; event is audit trail. */}
function repair_(q){(q.apps||[]).forEach(a=>event_(q,'repair',a.package,a.app_name,q.fixed,q.reason,q.group_id,q.note));/* Snapshot on next Sync Now supplies non-duplicating totals. */}
